
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"  # Вы можете изменить порт
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
